 print(current.previous,current.previous.data)
                        print(current,current.data)
                        print(current.next,current.next.data)
                        print(current.next.previous,current.next.previous.data)
                        print(current.previous.next,current.previous.next.data)